import {
  Home,
  ShoppingCart,
  Utensils,
  Beer,
  Shirt,
  Wrench,
  Plane,
  Heart,
  Monitor,
  ShoppingBag,
  Wallet,
  Book,
  User,
  Zap,
  MoreHorizontal,
  Coffee,
} from "lucide-react";

export const CATEGORIES = [
  { name: 'Rent', icon: Home, plannedKey: 'rent', spentKey: 'rent_spent' },
  { name: 'Groceries & Supermarkets', icon: ShoppingCart, plannedKey: 'groceries', spentKey: 'groceries_spent' },
  { name: 'Restaurants & Dining', icon: Utensils, plannedKey: 'dining_out', spentKey: 'dining_out_spent' },
  { name: 'Pubs & Bars', icon: Beer, plannedKey: 'entertainment', spentKey: 'entertainment_spent' },
  { name: 'Clothing & Apparel', icon: Shirt, plannedKey: 'shopping', spentKey: 'shopping_spent' },
  { name: 'Home & Hardware', icon: Wrench, plannedKey: 'miscellaneous', spentKey: 'miscellaneous_spent' },
  { name: 'Travel & Transportation', icon: Plane, plannedKey: 'transport', spentKey: 'transport_spent' },
  { name: 'Health & Fitness', icon: Heart, plannedKey: 'health_fitness', spentKey: 'health_fitness_spent' },
  { name: 'Entertainment & Leisure', icon: Monitor, plannedKey: 'entertainment', spentKey: 'entertainment_spent' },
  { name: 'Other Retail', icon: ShoppingBag, plannedKey: 'shopping', spentKey: 'shopping_spent' },
  { name: 'Money Transfer', icon: Wallet, plannedKey: 'miscellaneous', spentKey: 'miscellaneous_spent' },
  { name: 'Education', icon: Book, plannedKey: 'education', spentKey: 'education_spent' },
  { name: 'Personal Care', icon: User, plannedKey: 'personal_care', spentKey: 'personal_care_spent' },
  { name: 'Utilities & Bills', icon: Zap, plannedKey: 'utilities', spentKey: 'utilities_spent' },
  { name: 'Miscellaneous', icon: MoreHorizontal, plannedKey: 'miscellaneous', spentKey: 'miscellaneous_spent' },
  { name: 'Takeaway Coffee', icon: Coffee, plannedKey: 'dining_out', spentKey: 'dining_out_spent' },
] as const;