export interface Budget {
  id: string;
  user_id: string;
  month: number;
  year: number;
  created_at: string | null;
  salary: number;
  bonus: number;
  rent: number;
  groceries_supermarkets: number;
  restaurants_cafes_takeaway: number;
  pubs_bars: number;
  clothing_apparel: number;
  home_hardware: number;
  travel_transportation: number;
  health_pharmacy: number;
  entertainment_leisure: number;
  online_services_subscriptions: number;
  other_retail: number;
  money_transfer: number;
  education: number;
  personal_care: number;
  utilities_bills: number;
  miscellaneous: number;
  takeaway_coffee: number;
  rent_spent: number;
  groceries_supermarkets_spent: number;
  restaurants_cafes_takeaway_spent: number;
  pubs_bars_spent: number;
  clothing_apparel_spent: number;
  home_hardware_spent: number;
  travel_transportation_spent: number;
  health_pharmacy_spent: number;
  entertainment_leisure_spent: number;
  online_services_subscriptions_spent: number;
  other_retail_spent: number;
  money_transfer_spent: number;
  education_spent: number;
  personal_care_spent: number;
  utilities_bills_spent: number;
  miscellaneous_spent: number;
  takeaway_coffee_spent: number;
}

export type BudgetInsert = Omit<Budget, 'id' | 'created_at'>;
export type BudgetUpdate = Partial<BudgetInsert>;
