// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idvwqwlgbscbyjiylzin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkdndxd2xnYnNjYnlqaXlsemluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxOTM3MzUsImV4cCI6MjA1MTc2OTczNX0.kios5LjKb_tTWxbGbNw_KAehx1jo4RqKUIa__F_nKWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);